import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';

const el = (id) => document.getElementById(id);
const ui = { power: el('power'), speed: el('speed'), grade: el('grade'), time: el('time'), distance: el('distance'), elevation: el('elevation'), status: el('connection-status'), physics: el('physics') };
const state = { watts: 145, speed: 0, distance: 0, elapsed: 0, elevationGain: 0, paused: false, samples: [], lastSample: 0, connected: false, model: null };

const scene = new THREE.Scene(); scene.background = new THREE.Color('#91c9dd'); scene.fog = new THREE.Fog('#91c9dd', 90, 370);
const camera = new THREE.PerspectiveCamera(55, innerWidth / innerHeight, .1, 1000); camera.position.set(-9, 5.8, 13);
const renderer = new THREE.WebGLRenderer({ antialias:true, powerPreference:'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; el('scene').append(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping=true; controls.enablePan=false; controls.minDistance=7; controls.maxDistance=23; controls.maxPolarAngle=1.48;
scene.add(new THREE.HemisphereLight('#d9f2ff','#566634',2.2)); const sun=new THREE.DirectionalLight('#fff2d4',2.8);sun.position.set(-70,95,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);

const routeLength=8400, points=[];
function terrainHeight(x,z){ return 2.5*Math.sin(x/170)+4*Math.cos(z/220)+3*Math.sin((x+z)/190)+1.5*Math.cos((x-z)/130); }
function pointAt(s){ const q=s/routeLength, x=-340+680*q, z=68*Math.sin(q*Math.PI*2.2)+30*Math.sin(q*Math.PI*6.3); return new THREE.Vector3(x,terrainHeight(x,z)+.12,z); }
function heightAt(s){ return pointAt(s).y; }
for(let s=0;s<=routeLength;s+=10) points.push(pointAt(s));
const curve=new THREE.CatmullRomCurve3(points,false,'centripetal');
const groundGeo=new THREE.PlaneGeometry(900,900,80,80); const groundPos=groundGeo.attributes.position; for(let i=0;i<groundPos.count;i++) groundPos.setZ(i,terrainHeight(groundPos.getX(i),-groundPos.getY(i))); groundGeo.computeVertexNormals(); const ground=new THREE.Mesh(groundGeo,new THREE.MeshStandardMaterial({color:'#6e9b50',roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const roadVertices=[],roadIndices=[];for(let i=0;i<points.length;i++){const tangent=curve.getTangent(i/(points.length-1)).normalize(),side=new THREE.Vector3(-tangent.z,0,tangent.x).normalize().multiplyScalar(3.1),center=points[i].clone().add(new THREE.Vector3(0,.28,0));roadVertices.push(...center.clone().sub(side),...center.clone().add(side));if(i<points.length-1)roadIndices.push(i*2,i*2+1,i*2+2,i*2+1,i*2+3,i*2+2)}const roadGeometry=new THREE.BufferGeometry();roadGeometry.setAttribute('position',new THREE.Float32BufferAttribute(roadVertices,3));roadGeometry.setIndex(roadIndices);roadGeometry.computeVertexNormals();const road=new THREE.Mesh(roadGeometry,new THREE.MeshStandardMaterial({color:'#3c4245',roughness:.94,side:THREE.DoubleSide}));road.receiveShadow=true;scene.add(road);
const edgeMat=new THREE.MeshStandardMaterial({color:'#edf0e4'}); for(const side of [-3.02,3.02]){const pts=points.map((p,i)=>{const tangent=curve.getTangent(i/(points.length-1)).normalize();return p.clone().add(new THREE.Vector3(-tangent.z,0,tangent.x).multiplyScalar(side)).add(new THREE.Vector3(0,.08,0))});scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#e7e8dc'})));}

function tree(x,z,scale){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22*scale,.3*scale,2.5*scale,7),new THREE.MeshStandardMaterial({color:'#754b2c'}));trunk.position.y=1.25*scale;const crown=new THREE.Mesh(new THREE.ConeGeometry(1.4*scale,4.6*scale,8),new THREE.MeshStandardMaterial({color:['#315b36','#3f713d','#274f36'][Math.floor(Math.random()*3)]}));crown.position.y=4*scale;g.add(trunk,crown);g.position.set(x,terrainHeight(x,z),z);g.traverse(o=>o.castShadow=true);scene.add(g)}
for(let i=0;i<360;i++){const a=Math.random()*Math.PI*2,r=60+Math.random()*390;tree(Math.cos(a)*r,Math.sin(a)*r,.55+Math.random()*1.1)}

const rider=new THREE.Group(); const riderMat=new THREE.MeshStandardMaterial({color:'#f15f4e',roughness:.55}), dark=new THREE.MeshStandardMaterial({color:'#172127'}); const body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.05,5,10),riderMat);body.position.set(0,1.65,0);body.rotation.x=-.45;rider.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),new THREE.MeshStandardMaterial({color:'#e5a072'}));head.position.set(0,2.45,-.28);rider.add(head);
const bike=new THREE.Group();const wheelGeo=new THREE.TorusGeometry(.52,.045,8,18);for(const z of [-.72,.72]){const w=new THREE.Mesh(wheelGeo,dark);w.rotation.y=Math.PI/2;w.position.set(0,.55,z);bike.add(w)}const frame=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,1.35),riderMat);frame.rotation.x=.76;frame.position.y=.88;bike.add(frame);rider.add(bike);rider.traverse(o=>o.castShadow=true);scene.add(rider);

function routePose(distance){const t=((distance*8)%routeLength)/routeLength,p=curve.getPointAt(t),tan=curve.getTangentAt(t).normalize(),rawGrade=tan.y/Math.hypot(tan.x,tan.z)*100;return {p,tan,grade:Math.max(-10,Math.min(10,rawGrade))};}
const startingPose=routePose(0); controls.target.copy(startingPose.p).add(startingPose.tan.clone().multiplyScalar(7)).add(new THREE.Vector3(0,1.2,0)); camera.position.copy(startingPose.p).add(startingPose.tan.clone().multiplyScalar(-20)).add(new THREE.Vector3(0,18,0)); camera.lookAt(controls.target);
function updateUI(grade){ui.power.textContent=Math.round(state.watts);ui.speed.textContent=(state.speed*3.6).toFixed(1);ui.grade.textContent=grade.toFixed(1);const m=Math.floor(state.elapsed/60),s=Math.floor(state.elapsed%60);ui.time.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;ui.distance.textContent=(state.distance/1000).toFixed(2)+' km';ui.elevation.textContent=Math.round(state.elevationGain)+' m';if(state.model)ui.physics.textContent=`Physics: ${state.model.power} W × 97% = ${state.model.usable} W · gravity ${state.model.gravity} N · rolling ${state.model.rolling} N · aero ${state.model.aero} N`;}
function sample(){state.samples.push({time:state.elapsed,watts:Math.round(state.watts),speed:state.speed,dist:state.distance});}
function powerSpeed(power,grade){const mass=85,g=9.81,crr=.004,cda=.32,rho=1.225,usable=power*.97,gradeFraction=grade/100;let low=0,high=25;for(let i=0;i<30;i++){const v=(low+high)/2,force=mass*g*(crr+Math.max(gradeFraction,-.003))+.5*rho*cda*v*v;if(force*v>usable)high=v;else low=v;}const speed=grade<0?Math.min(25,low+Math.abs(grade)*.13):low;const gravity=mass*g*gradeFraction,rolling=mass*g*crr,aero=.5*rho*cda*speed*speed;state.model={power:Math.round(power),usable:Math.round(usable),gravity:gravity.toFixed(1),rolling:rolling.toFixed(1),aero:aero.toFixed(1)};return speed;}
let last=performance.now(),lastElevation=heightAt(0);
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;let pose=routePose(state.distance);if(!state.paused){const targetSpeed=powerSpeed(state.watts,pose.grade);state.speed+=Math.max(-4,Math.min(5,(targetSpeed-state.speed)*1.8))*dt;state.distance+=state.speed*dt;state.elapsed+=dt;const newHeight=heightAt(state.distance*8);state.elevationGain+=Math.max(0,newHeight-lastElevation);lastElevation=newHeight;if(now-state.lastSample>1000){sample();state.lastSample=now;}}
pose=routePose(state.distance);rider.position.copy(pose.p).add(new THREE.Vector3(0,.34,0));rider.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),pose.tan.clone().setY(0).normalize());rider.rotateX(-Math.asin(pose.tan.y));bike.children.forEach(o=>{if(o.geometry?.type==='TorusGeometry')o.rotation.z-=state.speed*dt/.52});const target=pose.p.clone().add(pose.tan.clone().multiplyScalar(7)).add(new THREE.Vector3(0,1.2,0));controls.target.lerp(target,.07);if(!controls.userMoved){const desired=pose.p.clone().add(pose.tan.clone().multiplyScalar(-17)).add(new THREE.Vector3(0,12,0));camera.position.lerp(desired,.025)}controls.update();updateUI(pose.grade);renderer.render(scene,camera);}
controls.addEventListener('start',()=>controls.userMoved=true);animate(performance.now());
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

const slider=el('power-slider');slider.addEventListener('input',()=>{if(!state.connected){state.watts=+slider.value;el('slider-output').value=state.watts+' W';}});
el('pause-button').onclick=()=>{state.paused=!state.paused;el('pause-button').textContent=state.paused?'Resume':'Pause';};
el('ble-button').onclick=async()=>{if(!navigator.bluetooth){ui.status.textContent='Web Bluetooth is unavailable here — simulation remains active.';return;}try{const device=await navigator.bluetooth.requestDevice({filters:[{services:[0x1818]}]});const server=await device.gatt.connect(),service=await server.getPrimaryService(0x1818),ch=await service.getCharacteristic(0x2A63);await ch.startNotifications();ch.addEventListener('characteristicvaluechanged',(event)=>{const v=event.target.value,flags=v.getUint16(0,true);state.watts=v.getInt16(2,true);state.connected=true;slider.disabled=true;ui.status.textContent=`Connected to ${device.name||'power meter'} · live power active`;});}catch(err){ui.status.textContent=`Could not connect: ${err.message}`;}};
el('export-button').onclick=()=>{if(!state.samples.length){ui.status.textContent='Ride a little longer before exporting.';return;}const start=new Date(Date.now()-state.elapsed*1000).toISOString();const track=state.samples.map(x=>`<Trackpoint><Time>${new Date(Date.parse(start)+x.time*1000).toISOString()}</Time><DistanceMeters>${x.dist.toFixed(1)}</DistanceMeters><Extensions><TPX xmlns="http://www.garmin.com/xmlschemas/ActivityExtension/v2"><Watts>${x.watts}</Watts><Speed>${x.speed.toFixed(2)}</Speed></TPX></Extensions></Trackpoint>`).join('');const tcx=`<?xml version="1.0"?><TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2"><Activities><Activity Sport="Biking"><Id>${start}</Id><Lap StartTime="${start}"><TotalTimeSeconds>${state.elapsed.toFixed(1)}</TotalTimeSeconds><DistanceMeters>${state.distance.toFixed(1)}</DistanceMeters><Track>${track}</Track></Lap></Activity></Activities></TrainingCenterDatabase>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([tcx],{type:'application/vnd.garmin.tcx+xml'}));a.download='veloworld-ride.tcx';a.click();URL.revokeObjectURL(a.href);ui.status.textContent='TCX downloaded — ready to upload to Strava.';};
